name: Reusable Workflow

on:
  workflow_call:
    inputs:
      pythonVersion:
        description: Setup your specific python version
        required: false
        type: string
        default: pypy3.9

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      
      - name: Print Hello World!
        run: echo Hello World!

      # - name: Install python sdk
      #   uses: actions/setup-python
      #   with:
      #     python-version: ${{ inputs.pythonVersion }}

      # - name: Print python env
      #   run: python3 -h
